### ISSUE TITLE
Topmost option when initiating PIP?

### ISSUE THREAD

**Issue by mdscott-g** [WICG/picture-in-picture#1]
On desktop, there's a couple of meaningful implementations/use cases for PIP.  One is traditional TV style PIP where you get an always-on-top window that remains topmost at all times.  However, a number of existing sites use pop-out windows which are non-topmost.   There are some positive properties of this; it's possible to watch content without taking up a browser-sized window, but if you do switch to larger app windows they're not obscured by the video.

Since I believe we're encouraging sites to deprecate legacy approaches like pop-out windows, it might be nice to allow them to request less intrusive non-topmost behavior (e.g via options).  Alternately, if both topmost and non-topmost are relevant, we might leave control with this purely with the UA (e.g. via some kind of "pin" affordance that toggles topmost status).

**Comment by mounirlamouri** [comment]
All native APIs for PIP are topmost so I'm not sure how this option could realistically happen. I'm not sure why someone wouldn't create a PIP window and ask for it not to be topmost. However, would it make sense to instead offer more options when creating a window so that it has minimal UI? Would that solve this use case?

**Comment by beaufortfrancois** [comment]
I agree with @mounirlamouri that the PiP Web API doesn't seem to a good place for this kind of behavior.
Web developers can already open non-topmost popup windows with:

```javascript
window.open('popup.html', 'My Popup', 'width=320,height=240');
```

**Comment by mounirlamouri** [comment]
I would be inclined to mark this as WontFix because I believe that PIP means topmost by default and I would be surprised if realistically we will get topmost `window.open()`. Probably worth re-opening if the use case is triggered later on.
