### ISSUE TITLE
PIP and page visibility

### ISSUE THREAD

**Issue by juberti** [WICG/picture-in-picture#110]
In the demo I am working on, we want to stop displaying video (and display some message) when the window is hidden. However, if we're pipped, we can't tell when we're minimized, because PIP always causes the visibility API to return 'visible'.

Would it be possible to add another property to the page visibility API to indicate PIP mode? This would allow a page using PIP to understand if its main document is still visible, which seems like something it would want to know.

See also #80.

**Comment by beaufortfrancois** [comment]
Thank you for filing this issue.

It looks like we may **not** want to force the Page Visibility API eventually to always return "visible" if there's a PiP element. Web developers could check the visibility state of both the page and the PiP video. 

```js
document.addEventListener('visibilitychange', function() {
  if (document.visibilityState == 'hidden') {
    // page is hidden (even if there's a PiP video)
  }
  if (document.pictureInPictureElement) {
    // there's a video playing in PiP
  }
});
```

What do you think @jernoble @mounirlamouri?

**Comment by jernoble** [comment]
I think that (whether rAF should fire) should be left as an implementation detail. I don’t want to handcuff future UAs by limiting performance optimizations.

Could this use case be better solved with intersection observers? It seems like @jubertii isn’t necessarily interested in the page’s overall visibility, but whether a certain portion of the page (not including the video in pip) is visible.

**Comment by jernoble** [comment]
Also, the same problem exists with the Remote Playback API. I’d rather not have to add different enums for visibilityState for each spec that has a “visible but...” behavior.

**Comment by juberti** [comment]
I'm interested in understanding whether the page (not including PIP) is overall visible.

My understanding is that intersection observers only solve whether an element is visible in the viewport, which isn't an issue for my scenario, as the video will always be in the viewport. (The question is whether the viewport is in fact visible to the user.)

**Comment by jernoble** [comment]
Right, that was my question: whether `intersectionObserver.observe(document.documentElement)` will trigger when the `document.visibilityState` would otherwise turn to `'hidden'`.

**Comment by jernoble** [comment]
Our local IntersectionObserver expert says this isn't part of the spec, so it looks like my workaround isn't going to be possible.

**Comment by jernoble** [comment]
Okay, so, three options:

1) Do nothing. The spec says "visible" unless the entire page is not visible at all, so we treat this use case as if only a tiny portion of the page was visible on the screen.
2) Add some "quasi-visible" state to the visibilityState. And hopefully do it in a spec-agnostic way so that other specs with the same issue get the benefit of the new enum state, and that means doing it in the [Page Visibility API](https://www.w3.org/TR/page-visibility/).
3) Decide that a minimized web view with a visible picture-in-picture presentation doesn't meet the language requirement that the "Document is at least partially visible on at least one screen", and allow the visibilityState to move to "hidden".

**Comment by juberti** [comment]
1) doesn't solve my problem, since I can't tell if the page is un-minimized when PIP is up.

3) would be easiest, I think, but I would suggest that we spec that rAF should still run (perhaps not mandatory), since otherwise I think that rAF definitely won't run, which would be bad. 

2) might be a future option once we understand the overall problem space better - I'm a bit reluctant to add in a lot of special cases to the PV API.

**Comment by jernoble** [comment]
I might be confused. Isn’t option 2 the one that adds special cases (new enums) to the PV API?

**Comment by juberti** [comment]
Sorry - markdown changed the option numbers on me. I updated the comment to avoid auto-numbering, it probably makes much more sense now.

**Comment by jernoble** [comment]
Gotcha. Ok with that clarification in mind, why must rAF still run when visibilityState is “hidden” and the video element is in PiP?

**Comment by juberti** [comment]
In cases where the PIP is being driven from a canvas, need some way to drive the redraw of the canvas. (Right now, I'm using setInterval, but that seems somewhat crufty.)

**Comment by jernoble** [comment]
Okay, then this sounds like a case of "having your cake and eating it too". :)

You want visibilityState === 'hidden' so you can detect when you're minimized (and presumably do less work), but you want rAF() to fire so you can do more work. And that's ignoring that rAF is a terrible way to paint video in the first place, since for anything other than 60 fps video, many of those rAF canvas paints will be painting the same frame as last time.  At least with setInterval, you can fire at approximately the frame rate of the underlying stream rather than the frame rate of the display.

**Comment by juberti** [comment]
it's the limitation of PIP that only a single video can be pipped :)

**Comment by jernoble** [comment]
Yeah, and what you're asking for is the ability to PiP a canvas, not a video element. That you're having to go from canvas->MediaStream->video rather than taking a canvas directly into PiP is evidence that this is a hacky solution, and maybe not something we should optimize for.

**Comment by mounirlamouri** [comment]
Isn't the issue that the canvas wouldn't redraw without rAF? If we can PIP a canvas directly, would this actually resolve the problem?

**Comment by juberti** [comment]
exactly, if we didn't get rAF, we wouldn't have a stable heartbeat to redraw the canvas.

**Comment by jernoble** [comment]
The difference, however, is that for the general case of a "video element in PiP", you don't need to rAF().  For the case of a "canvas element in PiP", it's self evident that you do. If we mandate that rAF _must_ fire when a "video element is in PiP", that will necessarily block off UA performance optimizations. If  we mandate that rAF _must_ fire when a "canvas element is in PiP", that doesn't affect the much more common case of a non-canvas backed video element in PiP.

**Comment by juberti** [comment]
I see where you're going with this; I'm fine with that approach.

**Comment by beaufortfrancois** [comment]
@juberti Can we close this issue now that https://github.com/WICG/picture-in-picture/pull/112 has been merged and we agree that Page Visibility events will fire independently of the visibility of the Picture-in-Picture window.
See https://wicg.github.io/picture-in-picture/#page-visibility

**Comment by juberti** [comment]
Closing per discussion.
