### ISSUE TITLE
Enter Picture-in-Picture without user activation if document.pictureInPictureElement is set

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/picture-in-picture#116]
@mounirlamouri suggested offline we may want to allow video to enter Picture-in-Picture without user activation if there's already a visible PiP window in the context of the document, in other words if  `document.pictureInPictureElement` is set.

```diff
  The {{requestPictureInPicture()}} method, when invoked, MUST
  return <a>a new promise</a> |promise| and run the following steps <a>in
  parallel</a>:

  1. Let |video| be the video element on which the method was invoked.
- 2. Let |userActivationRequired| be `true`.
+ 2. Let |userActivationRequired| be `true` if {{pictureInPictureElement}} is
+     null. It is `false` otherwise.
  3. Let |playingRequired| be `false`.
  4. Run the <a>request Picture-in-Picture algorithm</a> with |video|,
      |userActivationRequired|, and |playingRequired|.
```

This could help in situations where there are multiple video elements for one PiP media session.

What do you think @jernoble @scottlaw?

**Comment by mounirlamouri** [comment]
Note that this is an idea I had to help with some feedback we got from JWPlayer. They seem to be running ads and content in different `<video>` and being able to swap `<video>` on the fly would be helpful to them. We would need to experiment how good the transition would be but intuitively, I think we could do as good as when the `<video>` changes source.

**Comment by OrenMe** [comment]
I also support such an issue, and I was looking to see if someone already opened one as a matter of fact.
In client side ad insertion ads are usually played on another video tag to allow main content to load or keep buffering while ad is playing.
Switching between main content and ad content is in same video element is harder to manage, requiring to detach the source buffer and re attaching it, and this is if one has control over all aspects of the video and ad, which is, for example, not the case with popular ad SDK like IMA ada SDK.
Another aspect of this interactivity is additional controls over pip element, to enable skipping add or putting a notice that current content is an advertisement.
This can be like a media session control maybe type of interface.
Maybe this is already a different subject and requires a new issue. Let me know and I’ll open a separate one.

**Comment by scottlow** [comment]
I think this proposal makes sense.

@OrenMe I believe the controls scenario you're describing is covered by the [existing reference to Media Session](https://wicg.github.io/picture-in-picture/#media-session) and the [skipad action](https://wicg.github.io/mediasession/#actions-model) defined there.

**Comment by beaufortfrancois** [comment]
@OrenMe You may want to have a look at https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/l6sW0G4jzhE. We're going to experiment with a Skip Ad button in the Picture-in-Picture window.

![image](https://user-images.githubusercontent.com/634478/52265455-6c171100-2934-11e9-9fdf-3c6e16cccd1c.png)

**Comment by OrenMe** [comment]
thanks @scottlow, @beaufortfrancois - indeed it answers.
So having this and the user gesture will definitely answer this scenarios.
Usually for ads there's also the aspect of ad timer and ad timer to skip - are you also considering this somewhere?

**Comment by beaufortfrancois** [comment]
If @jernoble is OK with that change, spec will be [updated](https://github.com/WICG/picture-in-picture/pull/117/files).

**Comment by jernoble** [comment]
I'm OK with this. It has a low potential for misuse and a compelling use case.

**Comment by theIDinside** [comment]
Looking at this use case these days, why can't this problem be solved by script just changing the video source?

**Comment by beaufortfrancois** [comment]
It may not be possible depending on the website config to just changing the video source. It could be because of EME or MSE for instance.
