### ISSUE TITLE
Detail the reasons why PIP can't be triggered

### ISSUE THREAD

**Issue by mounirlamouri** [WICG/picture-in-picture#22]
3.1.5 says "If one can’t be created, throw a UnknownError and abort these steps."

I'm not sure `UnknownError` is the right exception to throw. Also, it might be good to give examples of why it can't be triggered. For example, if it is blocked by FeaturePolicy, we should probably do a `SecurityError`. Maybe check what other features do in that case. Another reason would be if the system blocked the feature for the application. Should the error be the same, I don't know.

**Comment by beaufortfrancois** [comment]
I agree if it is blocked by FeaturePolicy, it should definitely raise a `SecurityError`.
If it is blocked because screen is locked or webpage not visible then, we may want to throw `NotAllowedError`.
And if we don't know, `UnknownError` seems to be right call. WDYT?

**Comment by beaufortfrancois** [comment]
@mounirlamouri https://github.com/WICG/picture-in-picture/pull/27 addresses your concerns.
Note that the `SecurityError` bit was already there.
