### ISSUE TITLE
HTML Content

### ISSUE THREAD

**Issue by rektide** [WICG/picture-in-picture#26]
Hello. I'd love to be able to make a canvas or HTML content PIP. I had a remote spectrum analyzer project that renders in SVG, for example, that would be great to keep on screen while doing other work on my device.

**Comment by beaufortfrancois** [comment]
It is not in the scope of the initial version on the spec. We may consider this for an upcoming version.

As an alternative, you may want to use something like `window.open('remote-spectrum-analyzer.html');` move the popup window on a corner of the screen and use some software to make this window always on top.
