### ISSUE TITLE
Remove "top" and "start" positions in PictureInPicture options

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/picture-in-picture#5]
I believe we should let the UA (or OS) pick the preferred X and Y positions for the the PiP window. I'm not sure a website would know better than the OS what is better given a current setup (windows, workspaces).

**Comment by beaufortfrancois** [comment]
gentle ping @mounirlamouri

**Comment by mounirlamouri** [comment]
This is meant to be a hint to the system, not a mandatory position. My understanding is that this could be implemented on some platforms. Is this correct?

Happy to drop if there is no intention to implement. It's too early to speak for Chrome.

**Comment by beaufortfrancois** [comment]
With https://github.com/WICG/picture-in-picture/pull/29, we can close this issue.
