### ISSUE TITLE
What does happen to PictureInPictureWindow object when exitPictureInPicture?

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/picture-in-picture#54]
What does happen to PictureInPictureWindow object when exitPictureInPicture?
Should it be set to null?
Should its `width` and `height` dimensions reset? If so, would 0 makes sense?

What do you think @mounirlamouri?

**Comment by mounirlamouri** [comment]
That's an excellent question. We will probably have to add some lifecycle to the window object. We could simply return 0 but I think it might be interesting to look at what the DOM spec say for `Window`. We could expose a state into the object but I don't think `Window` has one.

**Comment by beaufortfrancois** [comment]
This snippet below resets `Window` dimensions to 0.

```js
var w = window.open("https://github.com");
w.onload = _ => {
  console.log(`Size: ${w.innerWidth}x${w.innerHeight}`);
  w.close();
  requestAnimationFrame(_ => {
    console.log(`Size: ${w.innerWidth}x${w.innerHeight}`);
  });
}
```
```
Size: 1500x878
Size: 0x0
```
