### ISSUE TITLE
Examples not work

### ISSUE THREAD

**Issue by BenjaminHoegh** [WICG/picture-in-picture#62]
The examples in this repository do not work at all. Not even the simple check for PiP support.

### This is how PiP work:

```js
    if (video.webkitSupportsPresentationMode && typeof video.webkitSetPresentationMode === "function") {
        // Toggle PiP when the user clicks the button.
        pipButtonElement.addEventListener("click", function(event) {
            video.webkitSetPresentationMode(video.webkitPresentationMode === "picture-in-picture" ? "inline" : "picture-in-picture");
        });
    } else {
        pipButtonElement.hidden= true;
    }
```

**Comment by beaufortfrancois** [comment]
Assuming `video` is an HTMLVideoElement and `pipButtonElement` an HTMLButtonElement on your page, this code works just fine.

**Comment by beaufortfrancois** [comment]
The examples in the repository are not yet implemented in browsers. You can follow the work in progress in implementation status page at https://github.com/WICG/picture-in-picture/blob/master/implementation-status.md

**Comment by BenjaminHoegh** [comment]
@beaufortfrancois The code I post is an example from Apple's website and works. I was talking about the examples you see at  https://wicg.github.io/picture-in-picture/

**Comment by beaufortfrancois** [comment]
The Picture-in-Picture API described in the spec is a draft and is currently being implemented in Chrome.

**Comment by BenjaminHoegh** [comment]
is this for mobile? or desktop?

**Comment by beaufortfrancois** [comment]
Both.

**Comment by BenjaminHoegh** [comment]
Well, then it's a big mystery that it doesn't work for me in Chrome or Safari. only the code I posted work in safari but not in Chrome

**Comment by beaufortfrancois** [comment]
The examples shown in this repo belongs to the spec of the Picture-in-Picture API that is NOT implemented yet by browsers. See https://github.com/WICG/picture-in-picture/blob/master/implementation-status.md

**Comment by beaufortfrancois** [comment]
Chrome doesn't support the `webkitSupportsPresentationMode` API. Only Safari.

**Comment by BenjaminHoegh** [comment]
wait what? So there is a picture-in-picture standard but safari use its own for now? and chrome only have it in development?

**Comment by beaufortfrancois** [comment]
This standard is very new and is being discussed as we speak.
For info, Safari shipped their version of Picture-in-Picture API in 2016.
