### ISSUE TITLE
"Picture In Picture" Is Overly Specific

### ISSUE THREAD

**Issue by phistuck** [WICG/picture-in-picture#67]
I know this is bikeshedding, but this specification is basically specifying an overlay window (or an always on top, chrome-less popup). "Picture in Picture" is an extremely awkward name (and long, too) for something that is meant to be extensible towards the general overlay.

**Comment by beaufortfrancois** [comment]
Thanks for your feedback @phistuck!

We're using "Picture-in-Picture" for several reasons:
- Android and Safari use this name already. Edge admittedly uses "Compact Overlay" but is often explained with the Picture-in-Picture string. See [example](https://www.windowscentral.com/compact-view-app)
- This spec is meant for video elements only
- This name is pretty popular in the TV landscape and convey what we're doing there 
- The overlay window contains media actions such as play/pause.

See our [explainer](https://github.com/WICG/picture-in-picture/blob/master/explainer.md)

**Comment by Mancerrss** [comment]
Yea I hope that browser only put the video on top of the Chrome less popup when the HTML5 video doesn't have any built in video player. I hope that it like get the video frame, resizes it and make it a popup, so the video player's controls and implementation is preserved, so it's not just constrained on the browser implemented UI and controls, so there's flexibility and liberty on controls on web dev's video player implementation

I'm not really a web dev, I'm just a UX designer so that's my UX and feature implementation suggestion

**Comment by tophf** [comment]
>This spec is meant for video elements only

Current edition, certainly.

>The API may be extended to allow an arbitrary element of the DOM to enter Picture-in-Picture

While this would make the feature exponentially more useful by exposing it for things like chat apps, news/finance tickers, webdev tools (eyedroppers/inspectors), and many others.

**Comment by Mancerrss** [comment]
That's a great idea @tophf this would bring up so many use cases and innovation for multi tasking on web scenarios

**Comment by beaufortfrancois** [comment]
I'm closing this as I've just added the `arbitrary-dom` label. We'll revisit this when we start thinking about allowing arbitrary DOM elements to request Picture-in-Picture.

**Comment by Yihao-G** [comment]
Just a note here.
One really useful case for some Japanese and Chinese users is it enables websites showing [Danmaku comments](https://www.researchgate.net/publication/322191160_Danmaku_vs_Forum_Comments_Understanding_User_Participation_and_Knowledge_Sharing_in_Online_Videos) on the videos. Even having [@Mancerrss 's propose](https://github.com/w3c/picture-in-picture/issues/67#issuecomment-390491917) above implemented would be quite helpful here.

**Comment by tophf** [comment]
> [Document PiP adds a new API](https://github.com/steimelchrome/document-pip-explainer/blob/main/explainer.md) to open an always-on-top window that can be populated with arbitrary HTMLElements
