### ISSUE TITLE
Resize event is not defined

### ISSUE THREAD

**Issue by mounirlamouri** [WICG/picture-in-picture#70]
Implementing this now and I'm assuming the event will not bubble nor be cancellable but having some writing about it would be nice :)

**Comment by beaufortfrancois** [comment]
By default `bubble` and `cancelable` are set to false for all events. This is why there were no mention of it. However you can find a PR that addresses your concerns at https://github.com/WICG/picture-in-picture/pull/71

The only related `resize` text we have is https://wicg.github.io/picture-in-picture/#eventdef-pictureinpicturewindow-resize

If we go that route, do we want to add `cancelable` as well to `enterPictureInPicture` and `exitPictureInPicture` algorithms?
https://wicg.github.io/picture-in-picture/#request-pip
https://wicg.github.io/picture-in-picture/#exit-pip

**Comment by mounirlamouri** [comment]
https://wicg.github.io/picture-in-picture/#eventdef-pictureinpicturewindow-resize IMO isn't really enough for spec language.
