### ISSUE TITLE
PiP can be triggered not only for a given video

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/picture-in-picture#8]
The explainer.md file says that

> The API will allow the website to check if Picture in Picture can be triggered for a given video.

However, the API only exposes `document.pictureInPictureEnabled` which tells only if Picture in Picture can be triggered, but not for a given video.

As the API only applies on `HTMLVideoElement` at the moment but is meant to be extensible, I'd rather update the sentence to _"The API will allow the website to check if Picture in Picture can be triggered"_.

What do you think @mounirlamouri?

**Comment by mounirlamouri** [comment]
That sounds reasonable. There is no mechanism I'm aware of that would prevent PIP to work for a given video. The first optional requirement would allow web pages to block user agent triggered PIP but regardless of the mechanism we chose, it would be triggered by the web page so we wouldn't have to expose whether the element can be PIP'd.

**Comment by beaufortfrancois** [comment]
For info, `<video>` with audio only actually fail to PiP in Safari as `video.webkitSupportsPresentationMode('picture-in-picture')` returns false.
