### ISSUE TITLE
Interaction with <video> element styles

### ISSUE THREAD

**Issue by ewoerner** [WICG/picture-in-picture#81]
Following example code:
```javascript
// example 1
video.style.display = 'none';
video.requestPictureInPicture();

// example 2
video.style.width = '10000px';
video.style.height = '10000px';
video.requestPictureInPicture();
```
I guess the expected outcome is that the style of the video element has no influence at all on how the video element is presented in picture-in-picture mode. Should this be clarified in the spec?

**Comment by beaufortfrancois** [comment]
You're right. It has no incidence on how video is presented in Picture-in-Picture.
Let me think about how to word this in the spec.

FYI @mounirlamouri

**Comment by beaufortfrancois** [comment]
See https://github.com/WICG/picture-in-picture/pull/83
